### ISSUE TITLE
Is Regressor compatible with shoulda-matchers 3.0.x?

### ISSUE THREAD

**Issue by secondstreetmedia** [ndea/regressor#21]
I'm getting:

`Bundler could not find compatible versions for gem "shoulda-matchers":`
`In Gemfile:`
`regressor (~> 0.6.0) ruby depends on`
`shoulda-matchers (>= 2.7.0, ~> 2.7.0) ruby`

`shoulda-matchers (~> 3.0.0) ruby`

If it is compatible, how should the two gems be specified in my gemfile?  If not, any plans for it to be soon?

Thanks,
Tim

**Comment by McRip** [comment]
:+1:

**Comment by erwinjunker** [comment]
I think it should be no problem to migrate to version 3.0.0 of shoulda matchers. Only thing you need to do when you upgrade to version 3.0.0 is to define your test framework because shoulda no longer detects the test framework automatically in version 3.0.0 (see https://robots.thoughtbot.com/shoulda-matchers-3-0). Also beware of default scopes because in 3.0.0 default scope are not considered anymore. Feel free to submit a pull request. I haven't tested regressor against version 3.0.0

**Comment by mminski** [comment]
Regressor tested with shoulder matchers  (~>3.0.0) and (=> 3.0.0). Works fine.
